<a href="https://colab.research.google.com/github/Gayathri-Patibandla/Data-Warehousing-Data-Mining/blob/main/Experiment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Data Pre-Processing Task Using Python Libraries....**

In [10]:
#import library
import pandas as pd
#Loading Planilha sem ttulo- global_education_data dataset
dataset=pd.read_csv("/content/Planilha sem ttulo - global_education_data new.csv")
#printing the first 5 records
dataset.head()

  Countries and areas    Latitude  ... Gross_Tertiary_Education_Enrollment  Unemployment_Rate
0         Afghanistan   3.393.911  ...                                 9.7              11.12
1             Albania  41.153.332  ...                                55.0              12.33
2             Algeria  28.033.886  ...                                51.4              11.70
3             Andorra  42.506.285  ...                                 0.0               0.00
4              Angola  11.202.692  ...                                 9.3               6.89

[5 rows x 29 columns]

**Identifying the Dependent and Independent Variable...**
In this Global educational dataset, the target variable is The 'Unemployment_Rate' which is dependent variable and the remaining variables are independent variable.

In [11]:
#Seperating independent and dependent variables
#dependent variable
y=dataset.Unemployment_Rate
#independent variable
X=dataset.drop(['Unemployment_Rate'],axis=1)
print(y)
print(X)

0      11.12
1      12.33
2      11.70
3       0.00
4       6.89
       ...
197     8.80
198     2.01
199    12.91
200    11.43
201     4.95
Name: Unemployment_Rate, Length: 202, dtype: float64
    Countries and areas  ... Gross_Tertiary_Education_Enrollment
0           Afghanistan  ...                                 9.7
1               Albania  ...                                55.0
2               Algeria  ...                                51.4
3               Andorra  ...                                 0.0
4                Angola  ...                                 9.3
..                  ...  ...                                 ...
197           Venezuela  ...                                79.3
198             Vietnam  ...                                28.5
199               Yemen  ...                                10.2
200              Zambia  ...                                 4.1
201            Zimbabwe  ...                                10.0

[202 rows x 28 columns]

**Checking for Missing Values...**

In [13]:
#Finding the records with no values
missing_values=dataset.isnull().sum()
print(missing_values)

Countries and areas                        0
Latitude                                   0
Longitude                                  0
OOSR_Pre0Primary_Age_Male                  0
OOSR_Pre0Primary_Age_Female                0
OOSR_Primary_Age_Male                      0
OOSR_Primary_Age_Female                    0
OOSR_Lower_Secondary_Age_Male              0
OOSR_Lower_Secondary_Age_Female            0
OOSR_Upper_Secondary_Age_Male              0
OOSR_Upper_Secondary_Age_Female            0
Completion_Rate_Primary_Male               0
Completion_Rate_Primary_Female             0
Completion_Rate_Lower_Secondary_Male       0
Completion_Rate_Lower_Secondary_Female     0
Completion_Rate_Upper_Secondary_Male       0
Completion_Rate_Upper_Secondary_Female     0
Grade_2_3_Proficiency_Reading              0
Grade_2_3_Proficiency_Math                 0
Primary_End_Proficiency_Reading            0
Primary_End_Proficiency_Math               0
Lower_Secondary_End_Proficiency_Reading    0
Lower_Secondary_End_Proficiency_Math       0
Youth_15_24_Literacy_Rate_Male             0
Youth_15_24_Literacy_Rate_Female           0
Birth_Rate                                 0
Gross_Primary_Education_Enrollment         0
Gross_Tertiary_Education_Enrollment        0
Unemployment_Rate                          0
dtype: int64